// soc_system_mm_interconnect_6.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 15.1 185

`timescale 1 ps / 1 ps
module soc_system_mm_interconnect_6 (
		input  wire        pll_0_outclk0_clk,                              //                            pll_0_outclk0.clk
		input  wire        render_dma_reset_n_reset_bridge_in_reset_reset, // render_dma_reset_n_reset_bridge_in_reset.reset
		input  wire [31:0] render_dma_mm_write_address,                    //                      render_dma_mm_write.address
		output wire        render_dma_mm_write_waitrequest,                //                                         .waitrequest
		input  wire [5:0]  render_dma_mm_write_burstcount,                 //                                         .burstcount
		input  wire [7:0]  render_dma_mm_write_byteenable,                 //                                         .byteenable
		input  wire        render_dma_mm_write_write,                      //                                         .write
		input  wire [63:0] render_dma_mm_write_writedata,                  //                                         .writedata
		output wire [28:0] pixel_filter_0_avm_s0_address,                  //                    pixel_filter_0_avm_s0.address
		output wire        pixel_filter_0_avm_s0_write,                    //                                         .write
		output wire [63:0] pixel_filter_0_avm_s0_writedata,                //                                         .writedata
		output wire [7:0]  pixel_filter_0_avm_s0_burstcount,               //                                         .burstcount
		output wire [7:0]  pixel_filter_0_avm_s0_byteenable,               //                                         .byteenable
		input  wire        pixel_filter_0_avm_s0_waitrequest               //                                         .waitrequest
	);

	wire          render_dma_mm_write_translator_avalon_universal_master_0_waitrequest;   // render_dma_mm_write_agent:av_waitrequest -> render_dma_mm_write_translator:uav_waitrequest
	wire   [63:0] render_dma_mm_write_translator_avalon_universal_master_0_readdata;      // render_dma_mm_write_agent:av_readdata -> render_dma_mm_write_translator:uav_readdata
	wire          render_dma_mm_write_translator_avalon_universal_master_0_debugaccess;   // render_dma_mm_write_translator:uav_debugaccess -> render_dma_mm_write_agent:av_debugaccess
	wire   [31:0] render_dma_mm_write_translator_avalon_universal_master_0_address;       // render_dma_mm_write_translator:uav_address -> render_dma_mm_write_agent:av_address
	wire          render_dma_mm_write_translator_avalon_universal_master_0_read;          // render_dma_mm_write_translator:uav_read -> render_dma_mm_write_agent:av_read
	wire    [7:0] render_dma_mm_write_translator_avalon_universal_master_0_byteenable;    // render_dma_mm_write_translator:uav_byteenable -> render_dma_mm_write_agent:av_byteenable
	wire          render_dma_mm_write_translator_avalon_universal_master_0_readdatavalid; // render_dma_mm_write_agent:av_readdatavalid -> render_dma_mm_write_translator:uav_readdatavalid
	wire          render_dma_mm_write_translator_avalon_universal_master_0_lock;          // render_dma_mm_write_translator:uav_lock -> render_dma_mm_write_agent:av_lock
	wire          render_dma_mm_write_translator_avalon_universal_master_0_write;         // render_dma_mm_write_translator:uav_write -> render_dma_mm_write_agent:av_write
	wire   [63:0] render_dma_mm_write_translator_avalon_universal_master_0_writedata;     // render_dma_mm_write_translator:uav_writedata -> render_dma_mm_write_agent:av_writedata
	wire    [8:0] render_dma_mm_write_translator_avalon_universal_master_0_burstcount;    // render_dma_mm_write_translator:uav_burstcount -> render_dma_mm_write_agent:av_burstcount
	wire          rsp_mux_src_valid;                                                      // rsp_mux:src_valid -> render_dma_mm_write_agent:rp_valid
	wire  [145:0] rsp_mux_src_data;                                                       // rsp_mux:src_data -> render_dma_mm_write_agent:rp_data
	wire          rsp_mux_src_ready;                                                      // render_dma_mm_write_agent:rp_ready -> rsp_mux:src_ready
	wire    [0:0] rsp_mux_src_channel;                                                    // rsp_mux:src_channel -> render_dma_mm_write_agent:rp_channel
	wire          rsp_mux_src_startofpacket;                                              // rsp_mux:src_startofpacket -> render_dma_mm_write_agent:rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                                // rsp_mux:src_endofpacket -> render_dma_mm_write_agent:rp_endofpacket
	wire   [63:0] pixel_filter_0_avm_s0_agent_m0_readdata;                                // pixel_filter_0_avm_s0_translator:uav_readdata -> pixel_filter_0_avm_s0_agent:m0_readdata
	wire          pixel_filter_0_avm_s0_agent_m0_waitrequest;                             // pixel_filter_0_avm_s0_translator:uav_waitrequest -> pixel_filter_0_avm_s0_agent:m0_waitrequest
	wire          pixel_filter_0_avm_s0_agent_m0_debugaccess;                             // pixel_filter_0_avm_s0_agent:m0_debugaccess -> pixel_filter_0_avm_s0_translator:uav_debugaccess
	wire   [31:0] pixel_filter_0_avm_s0_agent_m0_address;                                 // pixel_filter_0_avm_s0_agent:m0_address -> pixel_filter_0_avm_s0_translator:uav_address
	wire    [7:0] pixel_filter_0_avm_s0_agent_m0_byteenable;                              // pixel_filter_0_avm_s0_agent:m0_byteenable -> pixel_filter_0_avm_s0_translator:uav_byteenable
	wire          pixel_filter_0_avm_s0_agent_m0_read;                                    // pixel_filter_0_avm_s0_agent:m0_read -> pixel_filter_0_avm_s0_translator:uav_read
	wire          pixel_filter_0_avm_s0_agent_m0_readdatavalid;                           // pixel_filter_0_avm_s0_translator:uav_readdatavalid -> pixel_filter_0_avm_s0_agent:m0_readdatavalid
	wire          pixel_filter_0_avm_s0_agent_m0_lock;                                    // pixel_filter_0_avm_s0_agent:m0_lock -> pixel_filter_0_avm_s0_translator:uav_lock
	wire   [63:0] pixel_filter_0_avm_s0_agent_m0_writedata;                               // pixel_filter_0_avm_s0_agent:m0_writedata -> pixel_filter_0_avm_s0_translator:uav_writedata
	wire          pixel_filter_0_avm_s0_agent_m0_write;                                   // pixel_filter_0_avm_s0_agent:m0_write -> pixel_filter_0_avm_s0_translator:uav_write
	wire   [10:0] pixel_filter_0_avm_s0_agent_m0_burstcount;                              // pixel_filter_0_avm_s0_agent:m0_burstcount -> pixel_filter_0_avm_s0_translator:uav_burstcount
	wire          pixel_filter_0_avm_s0_agent_rf_source_valid;                            // pixel_filter_0_avm_s0_agent:rf_source_valid -> pixel_filter_0_avm_s0_agent_rsp_fifo:in_valid
	wire  [146:0] pixel_filter_0_avm_s0_agent_rf_source_data;                             // pixel_filter_0_avm_s0_agent:rf_source_data -> pixel_filter_0_avm_s0_agent_rsp_fifo:in_data
	wire          pixel_filter_0_avm_s0_agent_rf_source_ready;                            // pixel_filter_0_avm_s0_agent_rsp_fifo:in_ready -> pixel_filter_0_avm_s0_agent:rf_source_ready
	wire          pixel_filter_0_avm_s0_agent_rf_source_startofpacket;                    // pixel_filter_0_avm_s0_agent:rf_source_startofpacket -> pixel_filter_0_avm_s0_agent_rsp_fifo:in_startofpacket
	wire          pixel_filter_0_avm_s0_agent_rf_source_endofpacket;                      // pixel_filter_0_avm_s0_agent:rf_source_endofpacket -> pixel_filter_0_avm_s0_agent_rsp_fifo:in_endofpacket
	wire          pixel_filter_0_avm_s0_agent_rsp_fifo_out_valid;                         // pixel_filter_0_avm_s0_agent_rsp_fifo:out_valid -> pixel_filter_0_avm_s0_agent:rf_sink_valid
	wire  [146:0] pixel_filter_0_avm_s0_agent_rsp_fifo_out_data;                          // pixel_filter_0_avm_s0_agent_rsp_fifo:out_data -> pixel_filter_0_avm_s0_agent:rf_sink_data
	wire          pixel_filter_0_avm_s0_agent_rsp_fifo_out_ready;                         // pixel_filter_0_avm_s0_agent:rf_sink_ready -> pixel_filter_0_avm_s0_agent_rsp_fifo:out_ready
	wire          pixel_filter_0_avm_s0_agent_rsp_fifo_out_startofpacket;                 // pixel_filter_0_avm_s0_agent_rsp_fifo:out_startofpacket -> pixel_filter_0_avm_s0_agent:rf_sink_startofpacket
	wire          pixel_filter_0_avm_s0_agent_rsp_fifo_out_endofpacket;                   // pixel_filter_0_avm_s0_agent_rsp_fifo:out_endofpacket -> pixel_filter_0_avm_s0_agent:rf_sink_endofpacket
	wire          cmd_mux_src_valid;                                                      // cmd_mux:src_valid -> pixel_filter_0_avm_s0_agent:cp_valid
	wire  [145:0] cmd_mux_src_data;                                                       // cmd_mux:src_data -> pixel_filter_0_avm_s0_agent:cp_data
	wire          cmd_mux_src_ready;                                                      // pixel_filter_0_avm_s0_agent:cp_ready -> cmd_mux:src_ready
	wire    [0:0] cmd_mux_src_channel;                                                    // cmd_mux:src_channel -> pixel_filter_0_avm_s0_agent:cp_channel
	wire          cmd_mux_src_startofpacket;                                              // cmd_mux:src_startofpacket -> pixel_filter_0_avm_s0_agent:cp_startofpacket
	wire          cmd_mux_src_endofpacket;                                                // cmd_mux:src_endofpacket -> pixel_filter_0_avm_s0_agent:cp_endofpacket
	wire          render_dma_mm_write_agent_cp_valid;                                     // render_dma_mm_write_agent:cp_valid -> router:sink_valid
	wire  [145:0] render_dma_mm_write_agent_cp_data;                                      // render_dma_mm_write_agent:cp_data -> router:sink_data
	wire          render_dma_mm_write_agent_cp_ready;                                     // router:sink_ready -> render_dma_mm_write_agent:cp_ready
	wire          render_dma_mm_write_agent_cp_startofpacket;                             // render_dma_mm_write_agent:cp_startofpacket -> router:sink_startofpacket
	wire          render_dma_mm_write_agent_cp_endofpacket;                               // render_dma_mm_write_agent:cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                                       // router:src_valid -> cmd_demux:sink_valid
	wire  [145:0] router_src_data;                                                        // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                                       // cmd_demux:sink_ready -> router:src_ready
	wire    [0:0] router_src_channel;                                                     // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                               // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                                 // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          pixel_filter_0_avm_s0_agent_rp_valid;                                   // pixel_filter_0_avm_s0_agent:rp_valid -> router_001:sink_valid
	wire  [145:0] pixel_filter_0_avm_s0_agent_rp_data;                                    // pixel_filter_0_avm_s0_agent:rp_data -> router_001:sink_data
	wire          pixel_filter_0_avm_s0_agent_rp_ready;                                   // router_001:sink_ready -> pixel_filter_0_avm_s0_agent:rp_ready
	wire          pixel_filter_0_avm_s0_agent_rp_startofpacket;                           // pixel_filter_0_avm_s0_agent:rp_startofpacket -> router_001:sink_startofpacket
	wire          pixel_filter_0_avm_s0_agent_rp_endofpacket;                             // pixel_filter_0_avm_s0_agent:rp_endofpacket -> router_001:sink_endofpacket
	wire          router_001_src_valid;                                                   // router_001:src_valid -> rsp_demux:sink_valid
	wire  [145:0] router_001_src_data;                                                    // router_001:src_data -> rsp_demux:sink_data
	wire          router_001_src_ready;                                                   // rsp_demux:sink_ready -> router_001:src_ready
	wire    [0:0] router_001_src_channel;                                                 // router_001:src_channel -> rsp_demux:sink_channel
	wire          router_001_src_startofpacket;                                           // router_001:src_startofpacket -> rsp_demux:sink_startofpacket
	wire          router_001_src_endofpacket;                                             // router_001:src_endofpacket -> rsp_demux:sink_endofpacket
	wire          cmd_demux_src0_valid;                                                   // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [145:0] cmd_demux_src0_data;                                                    // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                                                   // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [0:0] cmd_demux_src0_channel;                                                 // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                                           // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                                             // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                                   // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [145:0] rsp_demux_src0_data;                                                    // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                                                   // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [0:0] rsp_demux_src0_channel;                                                 // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                                           // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                                             // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire          pixel_filter_0_avm_s0_agent_rdata_fifo_src_valid;                       // pixel_filter_0_avm_s0_agent:rdata_fifo_src_valid -> avalon_st_adapter:in_0_valid
	wire   [65:0] pixel_filter_0_avm_s0_agent_rdata_fifo_src_data;                        // pixel_filter_0_avm_s0_agent:rdata_fifo_src_data -> avalon_st_adapter:in_0_data
	wire          pixel_filter_0_avm_s0_agent_rdata_fifo_src_ready;                       // avalon_st_adapter:in_0_ready -> pixel_filter_0_avm_s0_agent:rdata_fifo_src_ready
	wire          avalon_st_adapter_out_0_valid;                                          // avalon_st_adapter:out_0_valid -> pixel_filter_0_avm_s0_agent:rdata_fifo_sink_valid
	wire   [65:0] avalon_st_adapter_out_0_data;                                           // avalon_st_adapter:out_0_data -> pixel_filter_0_avm_s0_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_out_0_ready;                                          // pixel_filter_0_avm_s0_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire    [0:0] avalon_st_adapter_out_0_error;                                          // avalon_st_adapter:out_0_error -> pixel_filter_0_avm_s0_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (64),
		.AV_BURSTCOUNT_W             (6),
		.AV_BYTEENABLE_W             (8),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (9),
		.USE_READ                    (0),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (8),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) render_dma_mm_write_translator (
		.clk                    (pll_0_outclk0_clk),                                                      //                       clk.clk
		.reset                  (render_dma_reset_n_reset_bridge_in_reset_reset),                         //                     reset.reset
		.uav_address            (render_dma_mm_write_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (render_dma_mm_write_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (render_dma_mm_write_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (render_dma_mm_write_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (render_dma_mm_write_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (render_dma_mm_write_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (render_dma_mm_write_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (render_dma_mm_write_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (render_dma_mm_write_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (render_dma_mm_write_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (render_dma_mm_write_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (render_dma_mm_write_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (render_dma_mm_write_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (render_dma_mm_write_burstcount),                                         //                          .burstcount
		.av_byteenable          (render_dma_mm_write_byteenable),                                         //                          .byteenable
		.av_write               (render_dma_mm_write_write),                                              //                          .write
		.av_writedata           (render_dma_mm_write_writedata),                                          //                          .writedata
		.av_beginbursttransfer  (1'b0),                                                                   //               (terminated)
		.av_begintransfer       (1'b0),                                                                   //               (terminated)
		.av_chipselect          (1'b0),                                                                   //               (terminated)
		.av_read                (1'b0),                                                                   //               (terminated)
		.av_readdata            (),                                                                       //               (terminated)
		.av_readdatavalid       (),                                                                       //               (terminated)
		.av_lock                (1'b0),                                                                   //               (terminated)
		.av_debugaccess         (1'b0),                                                                   //               (terminated)
		.uav_clken              (),                                                                       //               (terminated)
		.av_clken               (1'b1),                                                                   //               (terminated)
		.uav_response           (2'b00),                                                                  //               (terminated)
		.av_response            (),                                                                       //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                   //               (terminated)
		.av_writeresponsevalid  ()                                                                        //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (29),
		.AV_DATA_W                      (64),
		.UAV_DATA_W                     (64),
		.AV_BURSTCOUNT_W                (8),
		.AV_BYTEENABLE_W                (8),
		.UAV_BYTEENABLE_W               (8),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (11),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (8),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) pixel_filter_0_avm_s0_translator (
		.clk                    (pll_0_outclk0_clk),                                                    //                      clk.clk
		.reset                  (render_dma_reset_n_reset_bridge_in_reset_reset),                       //                    reset.reset
		.uav_address            (pixel_filter_0_avm_s0_agent_m0_address),                               // avalon_universal_slave_0.address
		.uav_burstcount         (pixel_filter_0_avm_s0_agent_m0_burstcount),                            //                         .burstcount
		.uav_read               (pixel_filter_0_avm_s0_agent_m0_read),                                  //                         .read
		.uav_write              (pixel_filter_0_avm_s0_agent_m0_write),                                 //                         .write
		.uav_waitrequest        (pixel_filter_0_avm_s0_agent_m0_waitrequest),                           //                         .waitrequest
		.uav_readdatavalid      (pixel_filter_0_avm_s0_agent_m0_readdatavalid),                         //                         .readdatavalid
		.uav_byteenable         (pixel_filter_0_avm_s0_agent_m0_byteenable),                            //                         .byteenable
		.uav_readdata           (pixel_filter_0_avm_s0_agent_m0_readdata),                              //                         .readdata
		.uav_writedata          (pixel_filter_0_avm_s0_agent_m0_writedata),                             //                         .writedata
		.uav_lock               (pixel_filter_0_avm_s0_agent_m0_lock),                                  //                         .lock
		.uav_debugaccess        (pixel_filter_0_avm_s0_agent_m0_debugaccess),                           //                         .debugaccess
		.av_address             (pixel_filter_0_avm_s0_address),                                        //      avalon_anti_slave_0.address
		.av_write               (pixel_filter_0_avm_s0_write),                                          //                         .write
		.av_writedata           (pixel_filter_0_avm_s0_writedata),                                      //                         .writedata
		.av_burstcount          (pixel_filter_0_avm_s0_burstcount),                                     //                         .burstcount
		.av_byteenable          (pixel_filter_0_avm_s0_byteenable),                                     //                         .byteenable
		.av_waitrequest         (pixel_filter_0_avm_s0_waitrequest),                                    //                         .waitrequest
		.av_read                (),                                                                     //              (terminated)
		.av_readdata            (64'b0000000000000000000000000000000011011110101011011101111010101101), //              (terminated)
		.av_begintransfer       (),                                                                     //              (terminated)
		.av_beginbursttransfer  (),                                                                     //              (terminated)
		.av_readdatavalid       (1'b0),                                                                 //              (terminated)
		.av_writebyteenable     (),                                                                     //              (terminated)
		.av_lock                (),                                                                     //              (terminated)
		.av_chipselect          (),                                                                     //              (terminated)
		.av_clken               (),                                                                     //              (terminated)
		.uav_clken              (1'b0),                                                                 //              (terminated)
		.av_debugaccess         (),                                                                     //              (terminated)
		.av_outputenable        (),                                                                     //              (terminated)
		.uav_response           (),                                                                     //              (terminated)
		.av_response            (2'b00),                                                                //              (terminated)
		.uav_writeresponsevalid (),                                                                     //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                  //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (145),
		.PKT_ORI_BURST_SIZE_L      (143),
		.PKT_RESPONSE_STATUS_H     (142),
		.PKT_RESPONSE_STATUS_L     (141),
		.PKT_QOS_H                 (130),
		.PKT_QOS_L                 (130),
		.PKT_DATA_SIDEBAND_H       (128),
		.PKT_DATA_SIDEBAND_L       (128),
		.PKT_ADDR_SIDEBAND_H       (127),
		.PKT_ADDR_SIDEBAND_L       (127),
		.PKT_BURST_TYPE_H          (126),
		.PKT_BURST_TYPE_L          (125),
		.PKT_CACHE_H               (140),
		.PKT_CACHE_L               (137),
		.PKT_THREAD_ID_H           (133),
		.PKT_THREAD_ID_L           (133),
		.PKT_BURST_SIZE_H          (124),
		.PKT_BURST_SIZE_L          (122),
		.PKT_TRANS_EXCLUSIVE       (109),
		.PKT_TRANS_LOCK            (108),
		.PKT_BEGIN_BURST           (129),
		.PKT_PROTECTION_H          (136),
		.PKT_PROTECTION_L          (134),
		.PKT_BURSTWRAP_H           (121),
		.PKT_BURSTWRAP_L           (121),
		.PKT_BYTE_CNT_H            (120),
		.PKT_BYTE_CNT_L            (110),
		.PKT_ADDR_H                (103),
		.PKT_ADDR_L                (72),
		.PKT_TRANS_COMPRESSED_READ (104),
		.PKT_TRANS_POSTED          (105),
		.PKT_TRANS_WRITE           (106),
		.PKT_TRANS_READ            (107),
		.PKT_DATA_H                (63),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_SRC_ID_H              (131),
		.PKT_SRC_ID_L              (131),
		.PKT_DEST_ID_H             (132),
		.PKT_DEST_ID_L             (132),
		.ST_DATA_W                 (146),
		.ST_CHANNEL_W              (1),
		.AV_BURSTCOUNT_W           (9),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) render_dma_mm_write_agent (
		.clk                   (pll_0_outclk0_clk),                                                      //       clk.clk
		.reset                 (render_dma_reset_n_reset_bridge_in_reset_reset),                         // clk_reset.reset
		.av_address            (render_dma_mm_write_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (render_dma_mm_write_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (render_dma_mm_write_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (render_dma_mm_write_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (render_dma_mm_write_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (render_dma_mm_write_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (render_dma_mm_write_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (render_dma_mm_write_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (render_dma_mm_write_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (render_dma_mm_write_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (render_dma_mm_write_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (render_dma_mm_write_agent_cp_valid),                                     //        cp.valid
		.cp_data               (render_dma_mm_write_agent_cp_data),                                      //          .data
		.cp_startofpacket      (render_dma_mm_write_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (render_dma_mm_write_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (render_dma_mm_write_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_src_valid),                                                      //        rp.valid
		.rp_data               (rsp_mux_src_data),                                                       //          .data
		.rp_channel            (rsp_mux_src_channel),                                                    //          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                              //          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                                //          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                                      //          .ready
		.av_response           (),                                                                       // (terminated)
		.av_writeresponsevalid ()                                                                        // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (145),
		.PKT_ORI_BURST_SIZE_L      (143),
		.PKT_RESPONSE_STATUS_H     (142),
		.PKT_RESPONSE_STATUS_L     (141),
		.PKT_BURST_SIZE_H          (124),
		.PKT_BURST_SIZE_L          (122),
		.PKT_TRANS_LOCK            (108),
		.PKT_BEGIN_BURST           (129),
		.PKT_PROTECTION_H          (136),
		.PKT_PROTECTION_L          (134),
		.PKT_BURSTWRAP_H           (121),
		.PKT_BURSTWRAP_L           (121),
		.PKT_BYTE_CNT_H            (120),
		.PKT_BYTE_CNT_L            (110),
		.PKT_ADDR_H                (103),
		.PKT_ADDR_L                (72),
		.PKT_TRANS_COMPRESSED_READ (104),
		.PKT_TRANS_POSTED          (105),
		.PKT_TRANS_WRITE           (106),
		.PKT_TRANS_READ            (107),
		.PKT_DATA_H                (63),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_SRC_ID_H              (131),
		.PKT_SRC_ID_L              (131),
		.PKT_DEST_ID_H             (132),
		.PKT_DEST_ID_L             (132),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (1),
		.ST_DATA_W                 (146),
		.AVS_BURSTCOUNT_W          (11),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) pixel_filter_0_avm_s0_agent (
		.clk                     (pll_0_outclk0_clk),                                      //             clk.clk
		.reset                   (render_dma_reset_n_reset_bridge_in_reset_reset),         //       clk_reset.reset
		.m0_address              (pixel_filter_0_avm_s0_agent_m0_address),                 //              m0.address
		.m0_burstcount           (pixel_filter_0_avm_s0_agent_m0_burstcount),              //                .burstcount
		.m0_byteenable           (pixel_filter_0_avm_s0_agent_m0_byteenable),              //                .byteenable
		.m0_debugaccess          (pixel_filter_0_avm_s0_agent_m0_debugaccess),             //                .debugaccess
		.m0_lock                 (pixel_filter_0_avm_s0_agent_m0_lock),                    //                .lock
		.m0_readdata             (pixel_filter_0_avm_s0_agent_m0_readdata),                //                .readdata
		.m0_readdatavalid        (pixel_filter_0_avm_s0_agent_m0_readdatavalid),           //                .readdatavalid
		.m0_read                 (pixel_filter_0_avm_s0_agent_m0_read),                    //                .read
		.m0_waitrequest          (pixel_filter_0_avm_s0_agent_m0_waitrequest),             //                .waitrequest
		.m0_writedata            (pixel_filter_0_avm_s0_agent_m0_writedata),               //                .writedata
		.m0_write                (pixel_filter_0_avm_s0_agent_m0_write),                   //                .write
		.rp_endofpacket          (pixel_filter_0_avm_s0_agent_rp_endofpacket),             //              rp.endofpacket
		.rp_ready                (pixel_filter_0_avm_s0_agent_rp_ready),                   //                .ready
		.rp_valid                (pixel_filter_0_avm_s0_agent_rp_valid),                   //                .valid
		.rp_data                 (pixel_filter_0_avm_s0_agent_rp_data),                    //                .data
		.rp_startofpacket        (pixel_filter_0_avm_s0_agent_rp_startofpacket),           //                .startofpacket
		.cp_ready                (cmd_mux_src_ready),                                      //              cp.ready
		.cp_valid                (cmd_mux_src_valid),                                      //                .valid
		.cp_data                 (cmd_mux_src_data),                                       //                .data
		.cp_startofpacket        (cmd_mux_src_startofpacket),                              //                .startofpacket
		.cp_endofpacket          (cmd_mux_src_endofpacket),                                //                .endofpacket
		.cp_channel              (cmd_mux_src_channel),                                    //                .channel
		.rf_sink_ready           (pixel_filter_0_avm_s0_agent_rsp_fifo_out_ready),         //         rf_sink.ready
		.rf_sink_valid           (pixel_filter_0_avm_s0_agent_rsp_fifo_out_valid),         //                .valid
		.rf_sink_startofpacket   (pixel_filter_0_avm_s0_agent_rsp_fifo_out_startofpacket), //                .startofpacket
		.rf_sink_endofpacket     (pixel_filter_0_avm_s0_agent_rsp_fifo_out_endofpacket),   //                .endofpacket
		.rf_sink_data            (pixel_filter_0_avm_s0_agent_rsp_fifo_out_data),          //                .data
		.rf_source_ready         (pixel_filter_0_avm_s0_agent_rf_source_ready),            //       rf_source.ready
		.rf_source_valid         (pixel_filter_0_avm_s0_agent_rf_source_valid),            //                .valid
		.rf_source_startofpacket (pixel_filter_0_avm_s0_agent_rf_source_startofpacket),    //                .startofpacket
		.rf_source_endofpacket   (pixel_filter_0_avm_s0_agent_rf_source_endofpacket),      //                .endofpacket
		.rf_source_data          (pixel_filter_0_avm_s0_agent_rf_source_data),             //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                          // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                          //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                           //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                          //                .error
		.rdata_fifo_src_ready    (pixel_filter_0_avm_s0_agent_rdata_fifo_src_ready),       //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (pixel_filter_0_avm_s0_agent_rdata_fifo_src_valid),       //                .valid
		.rdata_fifo_src_data     (pixel_filter_0_avm_s0_agent_rdata_fifo_src_data),        //                .data
		.m0_response             (2'b00),                                                  //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                                    //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (147),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) pixel_filter_0_avm_s0_agent_rsp_fifo (
		.clk               (pll_0_outclk0_clk),                                      //       clk.clk
		.reset             (render_dma_reset_n_reset_bridge_in_reset_reset),         // clk_reset.reset
		.in_data           (pixel_filter_0_avm_s0_agent_rf_source_data),             //        in.data
		.in_valid          (pixel_filter_0_avm_s0_agent_rf_source_valid),            //          .valid
		.in_ready          (pixel_filter_0_avm_s0_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (pixel_filter_0_avm_s0_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (pixel_filter_0_avm_s0_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (pixel_filter_0_avm_s0_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (pixel_filter_0_avm_s0_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (pixel_filter_0_avm_s0_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (pixel_filter_0_avm_s0_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (pixel_filter_0_avm_s0_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                                  // (terminated)
		.csr_read          (1'b0),                                                   // (terminated)
		.csr_write         (1'b0),                                                   // (terminated)
		.csr_readdata      (),                                                       // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),                   // (terminated)
		.almost_full_data  (),                                                       // (terminated)
		.almost_empty_data (),                                                       // (terminated)
		.in_empty          (1'b0),                                                   // (terminated)
		.out_empty         (),                                                       // (terminated)
		.in_error          (1'b0),                                                   // (terminated)
		.out_error         (),                                                       // (terminated)
		.in_channel        (1'b0),                                                   // (terminated)
		.out_channel       ()                                                        // (terminated)
	);

	soc_system_mm_interconnect_6_router router (
		.sink_ready         (render_dma_mm_write_agent_cp_ready),             //      sink.ready
		.sink_valid         (render_dma_mm_write_agent_cp_valid),             //          .valid
		.sink_data          (render_dma_mm_write_agent_cp_data),              //          .data
		.sink_startofpacket (render_dma_mm_write_agent_cp_startofpacket),     //          .startofpacket
		.sink_endofpacket   (render_dma_mm_write_agent_cp_endofpacket),       //          .endofpacket
		.clk                (pll_0_outclk0_clk),                              //       clk.clk
		.reset              (render_dma_reset_n_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                               //       src.ready
		.src_valid          (router_src_valid),                               //          .valid
		.src_data           (router_src_data),                                //          .data
		.src_channel        (router_src_channel),                             //          .channel
		.src_startofpacket  (router_src_startofpacket),                       //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                          //          .endofpacket
	);

	soc_system_mm_interconnect_6_router_001 router_001 (
		.sink_ready         (pixel_filter_0_avm_s0_agent_rp_ready),           //      sink.ready
		.sink_valid         (pixel_filter_0_avm_s0_agent_rp_valid),           //          .valid
		.sink_data          (pixel_filter_0_avm_s0_agent_rp_data),            //          .data
		.sink_startofpacket (pixel_filter_0_avm_s0_agent_rp_startofpacket),   //          .startofpacket
		.sink_endofpacket   (pixel_filter_0_avm_s0_agent_rp_endofpacket),     //          .endofpacket
		.clk                (pll_0_outclk0_clk),                              //       clk.clk
		.reset              (render_dma_reset_n_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                           //       src.ready
		.src_valid          (router_001_src_valid),                           //          .valid
		.src_data           (router_001_src_data),                            //          .data
		.src_channel        (router_001_src_channel),                         //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                   //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                      //          .endofpacket
	);

	soc_system_mm_interconnect_5_cmd_demux cmd_demux (
		.clk                (pll_0_outclk0_clk),                              //       clk.clk
		.reset              (render_dma_reset_n_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                               //      sink.ready
		.sink_channel       (router_src_channel),                             //          .channel
		.sink_data          (router_src_data),                                //          .data
		.sink_startofpacket (router_src_startofpacket),                       //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                         //          .endofpacket
		.sink_valid         (router_src_valid),                               //          .valid
		.src0_ready         (cmd_demux_src0_ready),                           //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                           //          .valid
		.src0_data          (cmd_demux_src0_data),                            //          .data
		.src0_channel       (cmd_demux_src0_channel),                         //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                   //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                      //          .endofpacket
	);

	soc_system_mm_interconnect_5_cmd_mux cmd_mux (
		.clk                 (pll_0_outclk0_clk),                              //       clk.clk
		.reset               (render_dma_reset_n_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                              //       src.ready
		.src_valid           (cmd_mux_src_valid),                              //          .valid
		.src_data            (cmd_mux_src_data),                               //          .data
		.src_channel         (cmd_mux_src_channel),                            //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                      //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                        //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                           //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                           //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                         //          .channel
		.sink0_data          (cmd_demux_src0_data),                            //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                   //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket)                      //          .endofpacket
	);

	soc_system_mm_interconnect_5_cmd_demux rsp_demux (
		.clk                (pll_0_outclk0_clk),                              //       clk.clk
		.reset              (render_dma_reset_n_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_001_src_ready),                           //      sink.ready
		.sink_channel       (router_001_src_channel),                         //          .channel
		.sink_data          (router_001_src_data),                            //          .data
		.sink_startofpacket (router_001_src_startofpacket),                   //          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                     //          .endofpacket
		.sink_valid         (router_001_src_valid),                           //          .valid
		.src0_ready         (rsp_demux_src0_ready),                           //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                           //          .valid
		.src0_data          (rsp_demux_src0_data),                            //          .data
		.src0_channel       (rsp_demux_src0_channel),                         //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                   //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                      //          .endofpacket
	);

	soc_system_mm_interconnect_5_rsp_mux rsp_mux (
		.clk                 (pll_0_outclk0_clk),                              //       clk.clk
		.reset               (render_dma_reset_n_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                              //       src.ready
		.src_valid           (rsp_mux_src_valid),                              //          .valid
		.src_data            (rsp_mux_src_data),                               //          .data
		.src_channel         (rsp_mux_src_channel),                            //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                      //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                        //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                           //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                           //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                         //          .channel
		.sink0_data          (rsp_demux_src0_data),                            //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                   //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket)                      //          .endofpacket
	);

	soc_system_mm_interconnect_1_avalon_st_adapter #(
		.inBitsPerSymbol (66),
		.inUsePackets    (0),
		.inDataWidth     (66),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (66),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (pll_0_outclk0_clk),                                // in_clk_0.clk
		.in_rst_0_reset (render_dma_reset_n_reset_bridge_in_reset_reset),   // in_rst_0.reset
		.in_0_data      (pixel_filter_0_avm_s0_agent_rdata_fifo_src_data),  //     in_0.data
		.in_0_valid     (pixel_filter_0_avm_s0_agent_rdata_fifo_src_valid), //         .valid
		.in_0_ready     (pixel_filter_0_avm_s0_agent_rdata_fifo_src_ready), //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                     //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                    //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                    //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                     //         .error
	);

endmodule
